name: CI - Github pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean build folder
        run: rm -rf build

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          FOLDER: build
          CLEAN: true
          BRANCH: gh-pages
